--  NOTE: Must happen before plugins are required (otherwise wrong leader will be used)
require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.telescope')
require('user.nvim-tree')
require('user.nvim-treesitter')
require('user.nvim-cmp')
require('user.lsp')
require('user.bufferline')
require('user.yank-highlight')
-- require('kickstart.plugins.autoformat')
require('user.null-ls')
require('user.copilot')
require('user.colorscheme')
require('user.harpoon')
