-- vim.opt.cursorline = true -- highlight the current line
-- vim.o.number = true

-- Lsp debug logs
-- vim.lsp.set_log_level("debug")
require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
spec "user.gitsigns"
spec "user.alpha"
spec "user.vim-tmux-navigator"
spec "user.graphql"
spec "user.diffview"
spec "user.netrw"
spec "user.project"
spec "user.indentline"
spec "user.bufdelete"
spec "user.autopairs"
spec "user.surround"
spec "user.markdown-preview"
spec "user.neotest"
-- nvim-dap
spec "user.vscode-js-debug"
spec "user.dap"
spec "user.dap-ui"
spec "user.dap-js"
spec "user.json5"

--extra
spec "user.tabby"
spec "user.neoscroll"
spec "user.illuminate"
spec "user.oil"
spec "user.ufo"
spec "user.lab"
spec "user.cellular-automaton"
spec "user.eyeliner"
spec "user.toggleterm"
spec "user.colorizer"
spec "user.dressing"
spec "user.oil"
spec "user.fidget"
spec "user.gitlinker"
spec "user.todo-comments"
spec "user.noice"
spec "user.neotab"
spec "user.navbuddy"
spec "user.copilot" --last

-- require "user.json5"
-- require "user.dap"
--
-- require "user.extras.matchup"
-- require "user.extras.modicator"
-- require "user.extras.rainbow"
-- require "user.extras.smoothie"

require "user.lazy"
