-- Fetch the variable from the shell and assign it into Neovim’s environment table:
local anthropic_key = os.getenv "ANTHROPIC_API_KEY"
vim.env.ANTHROPIC_API_KEY = anthropic_key

-- Lsp debug logs
-- vim.lsp.set_log_level("debug")

require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.whichkey"
spec "user.avante"
spec "user.opencode"
spec "user.mason"
spec "user.lspconfig"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
-- spec "user.nvim-treesitter"
spec "user.schemastore"
spec "user.copilot"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
-- Explorer
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine" -- bottom statusline
spec "user.navic"
-- spec "user.breadcrumbs"
spec "user.barbecue"
spec "user.harpoon"
spec "user.gitsigns"
spec "user.alpha"
spec "user.vim-tmux-navigator"
spec "user.graphql"
spec "user.polar"
spec "user.diffview"
spec "user.netrw"
spec "user.project"
spec "user.indentline"
spec "user.bufdelete"
spec "user.autopairs"
spec "user.surround"
spec "user.markdown-preview"
spec "user.neotest"
spec "user.json5"
spec "user.dap"
spec "user.nvim-ts-autotag"

--extra
spec "user.tabby"
spec "user.neoscroll"
spec "user.illuminate"
spec "user.oil"
spec "user.ufo"
spec "user.lab"
spec "user.cellular-automaton"
spec "user.eyeliner"
spec "user.toggleterm"
spec "user.colorizer"
spec "user.dressing"
spec "user.oil"
spec "user.fidget"
spec "user.gitlinker"
spec "user.todo-comments"
spec "user.noice"
spec "user.neotab"
spec "user.navbuddy"
spec "user.comment-highlights"
spec "user.blame"

require "user.extras.matchup"
-- require "user.extras.modicator"
-- require "user.extras.rainbow"
require "user.extras.smoothie"

require "user.lazy"
